# Site settings
title: Pico Future
description: Landing page for the picofuture website where we are working on improving the future one step at a time.

permalink: pretty

author:
  fullname: PicoFuture
  github: null
  linkedin: null
  email: null
  twitter: null

gtag: G-TG1ETWH58P

# Build settings
highlighter: rouge
markdown: kramdown

exclude: [
  'src',
  'webpack.mix.js',
  'tslint.json',
  'tsconfig.json',
  'package.json',
  'Gemfile',
  'Gemfile.lock',
  'node_modules',
  'tailwind.config.js',
  'package-lock.json',
  'mix-manifest.json',
  '.eslintrc',
  '.editorconfig',
  '.vscode',
  '.devcontainer',
  'LICENSE',
  'CNAME',
  '.gitignore',
  'definition-manifest.json',
  'README.md'
]
